### ISSUE TITLE
Testing new plugin

### ISSUE THREAD

**Issue by engrun** [willemsrb/sonar-packageanalyzer-plugin#1]
Hi, As requested we have now installed the new version, migrating from the older https://github.com/willemsrb/sonar-jdepend-plugin. 

However. According to the docs I should see a package cycles metrics. 
(I have not changed any config yet, no rulesets etc)

Where can I expect this metric to be shown in the user-interface?

**Comment by engrun** [comment]
I just enabled all the rules. 
Build now fails with

```
27-Apr-2017 16:02:46	[INFO] Sensor Package Analyzer Sensor (java) [packageanalyzer]
27-Apr-2017 16:02:46	[INFO] Build package model ...
27-Apr-2017 16:02:46	[INFO] JavaClasspath initialization
27-Apr-2017 16:02:46	[INFO] JavaClasspath initialization (done) | time=15ms
27-Apr-2017 16:02:46	[INFO] ------------------------------------------------------------------------
27-Apr-2017 16:02:46	[INFO] BUILD FAILURE
27-Apr-2017 16:02:46	[INFO] ------------------------------------------------------------------------
27-Apr-2017 16:02:46	[INFO] Total time: 19.063 s
27-Apr-2017 16:02:46	[INFO] Finished at: 2017-04-27T16:02:46+02:00
27-Apr-2017 16:02:46	[INFO] Final Memory: 96M/1035M
27-Apr-2017 16:02:46	[INFO] ------------------------------------------------------------------------
27-Apr-2017 16:02:46	[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project advisoradmin-server: null: MojoExecutionException: NullPointerException -> [Help 1]
27-Apr-2017 16:02:46	[ERROR] 
27-Apr-2017 16:02:46	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
27-Apr-2017 16:02:46	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
27-Apr-2017 16:02:46	[ERROR] 
27-Apr-2017 16:02:46	[ERROR] For more information about the errors and possible solutions, please read the following articles:
27-Apr-2017 16:02:46	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I've installed the plugin from source

**Comment by fmorgad0** [comment]
Hello there. I'm also testing your plugin and after enabling the package analyzer rules I can no longer scan projects. I'm using the 6.3 version of the server and 3.0.1.733 for the scanner. Any suggestions? Thanks in advance. 
![packageanalyzererror](https://cloud.githubusercontent.com/assets/11165415/25488861/09b25fe8-2b60-11e7-861d-d01b199031bf.jpg)

**Comment by willemsrb** [comment]
Hi Guys,

thank you for looking at the plugin. I've just returned from a vacation, so sorry for the late reply.

@engrun: The metric can be found under the complexity tab.

@fmorgad0: I'll have a look at the stacktrace tonight when i'm back home.

Regards,
Robert

**Comment by willemsrb** [comment]
@engrun: regarding the failing build; could you run with the -X option to show the stacktrace? Or is it the same as the one Filipe is experiencing?

**Comment by fmorgad0** [comment]
Hope you had a good trip! I appreciate the work you've done with JDepend and wanted to try this new version, since I feel that reporting issues exclusively on the package-info file might not provide enough information for developers. I only installed the 4KB "sonar-packageanalyzer-plugin-1.0-SNAPSHOT" JAR created by the plugin project, am I doing it right?  I had access to the new metric under the complexity tab and all, the problem is that after enabling the plugin rules in my quality profile I can no longer analyze projects, as shown in the screen shot above. 
Thanks again for the help!

**Comment by willemsrb** [comment]
Yes, you should only have to 'install' the JAR of the plugin project. It should however be around 4 MB; but because you do see the metric it think that must be a typo.

The stacktrace point to a piece of code that extracts the fully qualified classname of the type of a identifier. It seems you have an identifier that does not have a type (or something like that). I'll make it null-safe later on. However could you maybe enable debug logging and look at the debug logging just before the exception? Hopefully it can point you the the identifier (and its type) that is causing the problem. I would be interested in what kind of identifier would cause this problem so i can reproduce the problem locally.

**Comment by willemsrb** [comment]
Home ;)... i found a possible problem that could cause that NPE. In my local code it crashed when i used a fully qualified name in the code (eg. `java.net.InetAddress.getLocalHost().toString()`). I pushed the change; hopefully it also solves it at your end.

**Comment by willemsrb** [comment]
I just finished the main functionality of the plugin that registers the issues on relevant classes. As you said it was one of your main reasons to check the plugin i thought i would let you know. I changed the messages on the issues as compared to the Jdepend plugin to confirm to stating an action. Especially the package cycle message should now contain much more information.

**Comment by engrun** [comment]
I will test the updated plugin. However, I'm a bit confused, do will still need the package-info files?

**Comment by willemsrb** [comment]
Hi engrun,

you do not specifically *need* package-info files. The default setting is that the plugin will register issues on the package-info.java file if it exists. If it doesn't exist it will register issues on all classes that are 'relevant' for the issue in the package.

For example:

Package A contains classes A, B, and C and a package-info.java
Package B contains classes D, E, and F.

There is a package cycle between packages A and B when classes A and B reference classes from package B and classes D and E reference classes from package A.

An issue will be registered on the package-info.java in package A and issues will be registered on classes D and E in package B.

You can change this behaviour in the settings; i've documented the possibilities in the README.md. Please let me know if i should make parts more explicit to avoid confusion.

**Comment by engrun** [comment]
Ok, I have rebuilt the plugin and installed latest-greatest. The nullpointer no longer occurs. Great work! I'll have to test it a bit further to gather some results.

**Comment by fmorgad0** [comment]
Sorry for the late response @willemsrb. It was a typo, the plugin was indeed 4MB. I'm going to try the newer version out and post feedback later.

**Comment by willemsrb** [comment]
Thanks everybody! I hope the results are positive!
